"""news

Revision ID: 0902d5521fff
Revises: 
Create Date: 2025-11-01 00:57:27.590533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0902d5521fff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('processed_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('original_image', sa.LargeBinary(), nullable=True),
    sa.Column('watermarked_image_bg', sa.LargeBinary(), nullable=True),
    sa.Column('watermarked_image_wb', sa.LargeBinary(), nullable=True),
    sa.Column('watermarked_image_bg2', sa.LargeBinary(), nullable=True),
    sa.Column('watermarked_image_wb2', sa.LargeBinary(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('improved_sent', sa.Boolean(), nullable=False),
    sa.Column('discount_sent_290', sa.Boolean(), nullable=False),
    sa.Column('discount_sent_190', sa.Boolean(), nullable=False),
    sa.Column('discount_sent_99', sa.Boolean(), nullable=False),
    sa.Column('last_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('improved_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('discount_290_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('discount_190_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('discount_99_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_images_id'), 'processed_images', ['id'], unique=False)
    op.create_index(op.f('ix_processed_images_image_key'), 'processed_images', ['image_key'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processed_image_id'], ['processed_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_processed_images_image_key'), table_name='processed_images')
    op.drop_index(op.f('ix_processed_images_id'), table_name='processed_images')
    op.drop_table('processed_images')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
