"""news

Revision ID: b5ec269bb340
Revises: 0902d5521fff
Create Date: 2025-11-01 01:00:26.464448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ec269bb340'
down_revision: Union[str, Sequence[str], None] = '0902d5521fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('payments_processed_image_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'processed_images', ['processed_image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('processed_images', 'last_message_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=True)
    op.alter_column('processed_images', 'improved_message_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=True)
    op.alter_column('processed_images', 'discount_290_message_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=True)
    op.alter_column('processed_images', 'discount_190_message_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=True)
    op.alter_column('processed_images', 'discount_99_message_ids',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.ARRAY(sa.BigInteger()),
               existing_nullable=True)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.alter_column('processed_images', 'discount_99_message_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('processed_images', 'discount_190_message_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('processed_images', 'discount_290_message_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('processed_images', 'improved_message_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('processed_images', 'last_message_ids',
               existing_type=sa.ARRAY(sa.BigInteger()),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('payments_processed_image_id_fkey'), 'payments', 'processed_images', ['processed_image_id'], ['id'])
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('payments', 'updated_at')
    # ### end Alembic commands ###
