"""fixed

Revision ID: cfdc686bec19
Revises: 9ca896b25298
Create Date: 2025-11-04 00:58:51.314422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfdc686bec19'
down_revision: Union[str, Sequence[str], None] = '9ca896b25298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('original_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('standard_transparent_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('standard_bw_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('improved_transparent_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('improved_bw_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_transparent_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_bw_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_improved_transparent_file_id', sa.String(), nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_improved_bw_file_id', sa.String(), nullable=True))
    op.drop_column('processed_images', 'watermarked_image_bg2')
    op.drop_column('processed_images', 'watermarked_image_bg')
    op.drop_column('processed_images', 'original_image')
    op.drop_column('processed_images', 'watermarked_image_wb')
    op.drop_column('processed_images', 'watermarked_image_wb2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('watermarked_image_wb2', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_image_wb', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('processed_images', sa.Column('original_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_image_bg', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('processed_images', sa.Column('watermarked_image_bg2', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('processed_images', 'watermarked_improved_bw_file_id')
    op.drop_column('processed_images', 'watermarked_improved_transparent_file_id')
    op.drop_column('processed_images', 'watermarked_bw_file_id')
    op.drop_column('processed_images', 'watermarked_transparent_file_id')
    op.drop_column('processed_images', 'improved_bw_file_id')
    op.drop_column('processed_images', 'improved_transparent_file_id')
    op.drop_column('processed_images', 'standard_bw_file_id')
    op.drop_column('processed_images', 'standard_transparent_file_id')
    op.drop_column('processed_images', 'original_file_id')
    # ### end Alembic commands ###
